-- database_schema.sql
-- Relational Database Schema for Quantitative Trading Strategy Engine

-- 1. Stocks Table: Stores metadata about the equities being traded.
CREATE TABLE Stocks (
    stock_id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL UNIQUE,
    sector VARCHAR(50)
);

-- 2. Price_Data Table: Stores historical OHLCV data.
CREATE TABLE Price_Data (
    price_id SERIAL PRIMARY KEY,
    stock_id INTEGER NOT NULL,
    date DATE NOT NULL,
    open NUMERIC(15, 4),
    high NUMERIC(15, 4),
    low NUMERIC(15, 4),
    close NUMERIC(15, 4),
    volume BIGINT,
    FOREIGN KEY (stock_id) REFERENCES Stocks(stock_id) ON DELETE CASCADE,
    UNIQUE (stock_id, date) -- Prevent duplicate entries for the same stock on the same day
);

-- Index for efficient time-series querying and joining
CREATE INDEX idx_price_data_stock_date ON Price_Data(stock_id, date);

-- 3. Trading_Signals Table: Stores signals generated by the quantitative strategy (e.g., Mean Reversion).
CREATE TABLE Trading_Signals (
    signal_id SERIAL PRIMARY KEY,
    stock_id INTEGER NOT NULL,
    date DATE NOT NULL,
    signal_type VARCHAR(10) NOT NULL CHECK (signal_type IN ('BUY', 'SELL', 'HOLD')),
    indicator_value NUMERIC(15, 4), -- e.g., the calculated Z-score
    FOREIGN KEY (stock_id) REFERENCES Stocks(stock_id) ON DELETE CASCADE,
    UNIQUE (stock_id, date)
);

-- Index for quickly finding signals for a specific stock over time
CREATE INDEX idx_trading_signals_stock_date ON Trading_Signals(stock_id, date);

-- 4. Trades Table: Logs executed trades during backtesting or live trading.
CREATE TABLE Trades (
    trade_id SERIAL PRIMARY KEY,
    stock_id INTEGER NOT NULL,
    entry_date DATE NOT NULL,
    exit_date DATE,
    entry_price NUMERIC(15, 4) NOT NULL,
    exit_price NUMERIC(15, 4),
    profit_loss NUMERIC(15, 4), -- PnL realized on exit
    FOREIGN KEY (stock_id) REFERENCES Stocks(stock_id) ON DELETE CASCADE
);

-- Optional: Index on exit_date to quickly find open trades (where exit_date IS NULL)
CREATE INDEX idx_trades_exit_date ON Trades(exit_date);

-- 5. Portfolio_Performance Table: Tracks the aggregate portfolio value and daily returns.
CREATE TABLE Portfolio_Performance (
    id SERIAL PRIMARY KEY,
    stock_id INTEGER NOT NULL,
    date DATE NOT NULL,
    portfolio_value NUMERIC(18, 4) NOT NULL,
    daily_return NUMERIC(10, 6),
    FOREIGN KEY (stock_id) REFERENCES Stocks(stock_id) ON DELETE CASCADE
);
